// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Threadly.Infrastructure.Persistence;

#nullable disable

namespace Threadly.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ThreadlyDbContext))]
    [Migration("20261006133517_AddCommentaryAttachments")]
    partial class AddCommentaryAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Threadly.Domain.Commentaries.Commentary", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "CreatedAtUtc", "Id");

                    b.ToTable("Commentaries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Commentaries_ParentId_NotSelf", "[ParentId] <> [Id]");
                        });
                });

            modelBuilder.Entity("Threadly.Domain.Commentaries.CommentaryAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentaryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int?>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentaryId", "Position")
                        .IsUnique();

                    b.ToTable("CommentaryAttachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_CommentaryAttachments_Content", "[Size] > 0 AND [Size] <= 2097152 AND DATALENGTH([Content]) = [Size]");

                            t.HasCheckConstraint("CK_CommentaryAttachments_Position", "[Position] >= 0 AND [Position] < 10");

                            t.HasCheckConstraint("CK_CommentaryAttachments_Type", "([ContentType] = 'text/plain' AND [Width] IS NULL AND [Height] IS NULL AND [Size] <= 102400) OR ([ContentType] IN ('image/jpeg', 'image/png', 'image/gif') AND [Width] IS NOT NULL AND [Height] IS NOT NULL AND [Width] BETWEEN 1 AND 320 AND [Height] BETWEEN 1 AND 240)");
                        });
                });

            modelBuilder.Entity("Threadly.Domain.Commentaries.Commentary", b =>
                {
                    b.HasOne("Threadly.Domain.Commentaries.Commentary", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Threadly.Domain.Commentaries.CommentaryAttachment", b =>
                {
                    b.HasOne("Threadly.Domain.Commentaries.Commentary", null)
                        .WithMany("Attachments")
                        .HasForeignKey("CommentaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Threadly.Domain.Commentaries.Commentary", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
