<Project Sdk="Aspire.AppHost.Sdk/13.6.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>8b8fd130-a753-4b97-80fa-45ff7bcf2b37</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Docker" />
    <PackageReference Include="Aspire.Hosting.JavaScript" />
    <ProjectReference Include="..\..\src\Threadly.Api\Threadly.Api.csproj" />
  </ItemGroup>

</Project>
